class ExistentUser implements Exception {

    getMessage() => "Nombre de usuario existente.";
}